name = "lojinha-do-ze-backend"
main = "src/server.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://lojinha-do-ze.vercel.app"
ALLOWED_ORIGINS = "https://lojinha-do-ze.vercel.app,http://localhost:3000"
TRUST_PROXY = "true"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "lojinha-do-ze-bucket"